# Generated by Django 5.0.7 on 2024-07-17 11:29

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import exercises.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('primary_muscles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('abdominals', 'Abdominals'), ('hamstrings', 'Hamstrings'), ('adductors', 'Adductors'), ('quadriceps', 'Quadriceps'), ('biceps', 'Biceps'), ('shoulders', 'Shoulders'), ('chest', 'Chest'), ('middle back', 'Middle Back'), ('calves', 'Calves'), ('glutes', 'Glutes'), ('lower back', 'Lower Back'), ('lats', 'Lats'), ('triceps', 'Triceps'), ('traps', 'Traps'), ('forearms', 'Forearms'), ('neck', 'Neck'), ('abductors', 'Abductors')], max_length=20), blank=True, null=True, size=None)),
                ('secondary_muscles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('abdominals', 'Abdominals'), ('hamstrings', 'Hamstrings'), ('adductors', 'Adductors'), ('quadriceps', 'Quadriceps'), ('biceps', 'Biceps'), ('shoulders', 'Shoulders'), ('chest', 'Chest'), ('middle back', 'Middle Back'), ('calves', 'Calves'), ('glutes', 'Glutes'), ('lower back', 'Lower Back'), ('lats', 'Lats'), ('triceps', 'Triceps'), ('traps', 'Traps'), ('forearms', 'Forearms'), ('neck', 'Neck'), ('abductors', 'Abductors')], max_length=20), blank=True, null=True, size=None)),
                ('force', models.CharField(blank=True, choices=[('pull', 'Pull'), ('push', 'Push'), ('static', 'Static')], max_length=10, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=15)),
                ('mechanic', models.CharField(blank=True, choices=[('compound', 'Compound'), ('isolation', 'Isolation')], max_length=10, null=True)),
                ('equipment', models.CharField(blank=True, choices=[('body only', 'Body Only'), ('machine', 'Machine'), ('other', 'Other'), ('foam roll', 'Foam Roll'), ('kettlebells', 'Kettlebells'), ('dumbbell', 'Dumbbell'), ('cable', 'Cable'), ('barbell', 'Barbell'), ('bands', 'Bands'), ('medicine ball', 'Medicine Ball'), ('exercise ball', 'Exercise Ball'), ('e-z curl bar', 'Ez Curl Bar')], max_length=20, null=True)),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('stretching', 'Stretching'), ('plyometrics', 'Plyometrics'), ('strongman', 'Strongman'), ('powerlifting', 'Powerlifting'), ('cardio', 'Cardio'), ('olympic weightlifting', 'Olympic Weightlifting')], max_length=25)),
                ('instructions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('description', models.TextField(blank=True, null=True)),
                ('tips', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField()),
                ('repetitions', models.PositiveIntegerField()),
                ('pause_time', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
            ],
            options={
                'db_table': 'exercise_sets',
            },
        ),
        migrations.CreateModel(
            name='PlanForDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[(exercises.models.DayOfWeek['MONDAY'], 'Monday'), (exercises.models.DayOfWeek['TUESDAY'], 'Tuesday'), (exercises.models.DayOfWeek['WEDNESDAY'], 'Wednesday'), (exercises.models.DayOfWeek['THURSDAY'], 'Thursday'), (exercises.models.DayOfWeek['FRIDAY'], 'Friday'), (exercises.models.DayOfWeek['SATURDAY'], 'Saturday'), (exercises.models.DayOfWeek['SUNDAY'], 'Sunday')], max_length=10)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('begin_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('exercise_sets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exerciseset')),
            ],
            options={
                'db_table': 'workout_plans',
            },
        ),
    ]
