# Generated by Django 5.0.7 on 2024-07-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planforday',
            old_name='day_of_week',
            new_name='day_name',
        ),
        # Remove the AlterField operations for begin_time and end_time in PlanForDay
        # as they should remain TimeField
        migrations.AlterModelTable(
            name='planforday',
            table='plan_for_day',
        ),
        migrations.CreateModel(
            name='WorkoutRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_name', models.CharField(max_length=100)),
                ('begin_time', models.DateTimeField(blank=True, null=True)),  # Changed to DateTimeField
                ('end_time', models.DateTimeField(blank=True, null=True)),  # Changed to DateTimeField
                ('is_current', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('plans_for_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.planforday')),
            ],
        ),
    ]