# Generated by Django 5.0.7 on 2024-07-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_rename_day_of_week_planforday_day_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planforday',
            name='temp_begin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planforday',
            name='temp_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutroutine',
            name='temp_begin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutroutine',
            name='temp_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planforday',
            name='begin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planforday',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutroutine',
            name='begin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutroutine',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
