# Generated by Django 5.0.7 on 2024-07-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_planforday_temp_begin_date_planforday_temp_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planforday',
            name='begin_time',
        ),
        migrations.RemoveField(
            model_name='planforday',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workoutroutine',
            name='begin_time',
        ),
        migrations.RemoveField(
            model_name='workoutroutine',
            name='end_time',
        ),
    ]
