# Generated by Django 5.0.7 on 2024-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_planforday_begin_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutroutine',
            old_name='temp_begin_date',
            new_name='begin_date',
        ),
        migrations.RenameField(
            model_name='workoutroutine',
            old_name='temp_end_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='planforday',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterModelTable(
            name='workoutroutine',
            table='workout_routines',
        ),
    ]
