# Generated by Django 5.0.7 on 2024-07-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_rename_temp_begin_date_workoutroutine_begin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutroutine',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
