# Generated by Django 5.0.7 on 2024-07-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_user'),
    ]

    operations = [
         migrations.RunSQL(
            sql='DROP TABLE IF EXISTS users CASCADE;',
            reverse_sql='CREATE TABLE users (id uuid NOT NULL PRIMARY KEY);'  # To jest uproszczona wersja, dostosuj według potrzeb
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS users_groups CASCADE;',
            reverse_sql='CREATE TABLE users_groups (id serial NOT NULL PRIMARY KEY);'
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS users_user_permissions CASCADE;',
            reverse_sql='CREATE TABLE users_user_permissions (id serial NOT NULL PRIMARY KEY);'
        ),
    ]
