# Generated by Django 5.0.7 on 2024-07-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_remove_users_table'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='User',
                ),
            ],
        ),
    ]
