# Generated by Django 5.0.7 on 2024-07-22 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_remove_planforday_temp_begin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='planforday',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
