# Generated by Django 5.0.7 on 2024-08-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_alter_exerciseset_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_media_links',
        ),
    ]
