# Generated by Django 5.0.7 on 2024-08-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0015_remove_user_social_media_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disliked_exercises',
        ),
    ]
