# Generated by Django 5.0.7 on 2024-08-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_remove_user_disliked_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bmi',
            field=models.FloatField(blank=True, editable=False, help_text='Body Mass Index', null=True),
        ),
    ]
