# Generated by Django 5.0.7 on 2024-08-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_user_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_sport',
            field=models.CharField(blank=True, choices=[('strength', 'Strength'), ('stretching', 'Stretching'), ('plyometrics', 'Plyometrics'), ('strongman', 'Strongman'), ('powerlifting', 'Powerlifting'), ('cardio', 'Cardio'), ('olympic weightlifting', 'Olympic Weightlifting')], max_length=25, null=True),
        ),
    ]
