# Generated by Django 5.0.7 on 2024-08-07 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0018_user_preferred_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='workout_routines',
        ),
        migrations.AddField(
            model_name='workoutroutine',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_workout_routines', to=settings.AUTH_USER_MODEL),
        ),
    ]
