# Generated by Django 5.0.7 on 2024-08-08 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0021_alter_exerciseset_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planforday',
            name='exercise_sets',
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='plan_for_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='exercises.planforday'),
        ),
    ]
